### ISSUE TITLE
Labels on 2 charts are missing

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/surveys#13]
See the legends on these two graphics. The issue is that SurveyMonkey never required a full set of labels for these 1-10 ratings questions.

https://github.com/cncf/surveys/blob/master/maintainer/2019/Experience-h2.png
https://github.com/cncf/surveys/blob/master/maintainer/2019/Recommend-h2.png

**Comment by amye** [comment]
There's a PR in to resolve this.
