### ISSUE TITLE
Clarify purpose

### ISSUE THREAD

**Issue by lizrice** [cncf/surveys#2]
It's impossible to say anything meaningful about these survey questions without understanding who the intended respondents are. Is this for 

- existing maintainers?
- the TOC community? 
- prospective maintainers? 
- the wider CNCF community? 
- other interested parties like GB members, sponsors etc?

**Comment by caniszczyk** [comment]
The intended audience is folks who have interacted with the TOC, through a meeting or some other interaction. Happy to scope it further.

I'd love to ask questions regarding if people are happy with the TOC meeting, is it useful for them? Are they happy with response times? What else could the TOC be doing?

Essentially looking for a more data driven approach to planning given that our community has grown so much.

**Comment by caniszczyk** [comment]
older issue, we rectified this and published the first cncf toc survey results here: https://github.com/cncf/surveys/pull/20

we will be sending a note out with all maintainer/toc survey results out next week to the toc list
