### ISSUE TITLE
Issue with CNCF Cloud Native Survey 2021: Part 2

### ISSUE THREAD

**Issue by Falco20019** [cncf/surveys#36]
Dear CNCF-Team,

the current survey at https://www.surveymonkey.com/r/LZJ9DD7 has a bug. There are 2-3 questions where you have to rate per row from 1 to 5, but you can only choose each number once through-out all rows. Looks like the wrong question type (ranking) was chosen.

Please fix as soon as possible to avoid getting too many wrong results.

(I also sent this out to info@cncf.io, hoping to get this fixed ASAP.)

**Comment by amye** [comment]
We're on it!
