### ISSUE TITLE
Add a table that goes over basic maintainer survey data in the top level README.md

### ISSUE THREAD

**Issue by caniszczyk** [cncf/surveys#39]
e.g, overall satisfaction + NPS score + response time with satisfaction

**Comment by caniszczyk** [comment]
put a table here in a README.md https://github.com/cncf/surveys/tree/master/maintainer

So we have a rough summary how we are doing each year

**Comment by idvoretskyi** [comment]
+1, sounds good!

**Comment by caniszczyk** [comment]
@idvoretskyi friendly ping here

**Comment by idvoretskyi** [comment]
@caniszczyk yep, in progress

**Comment by caniszczyk** [comment]
@idvoretskyi ping :)?

**Comment by idvoretskyi** [comment]
@caniszczyk yes! Submitted here- https://github.com/cncf/surveys/pull/46
