### ISSUE TITLE
Can we upload this file?

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/surveys#57]
Please upload and add a link titled "Survey Reference Model" to https://github.com/cncf/surveys/tree/main/cloudnative

[CNCF 2022 Survey Reference Model.pdf](https://github.com/cncf/surveys/files/10667421/CNCF.2022.Survey.Reference.Model.pdf)

**Comment by amye** [comment]
We will take PRs!

**Comment by LawrenceHecht** [comment]
Let's see if my PR works.
